-- ═══════════════════════════════════════
-- worldcup_characters 테이블 생성
-- ═══════════════════════════════════════

CREATE TABLE IF NOT EXISTS worldcup_characters (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category     TEXT NOT NULL CHECK (category IN ('protagonist', 'rival', 'female')),
  name_ko      TEXT NOT NULL,
  name_en      TEXT,
  work_ko      TEXT NOT NULL,
  work_en      TEXT,
  tagline_ko   TEXT,
  tagline_en   TEXT,
  quote_ko     TEXT,
  quote_en     TEXT,
  anilist_id   INTEGER,
  mal_id       INTEGER,
  override_image_url TEXT,
  popularity_tier TEXT NOT NULL DEFAULT 'B' CHECK (popularity_tier IN ('S', 'A', 'B')),
  archetype    TEXT,
  trait         TEXT,
  tone         TEXT,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_wc_chars_active ON worldcup_characters (is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_wc_chars_category ON worldcup_characters (category);
CREATE INDEX IF NOT EXISTS idx_wc_chars_work ON worldcup_characters (work_ko);
CREATE INDEX IF NOT EXISTS idx_wc_chars_tier ON worldcup_characters (popularity_tier);

-- RLS 정책 (읽기 전용 공개)
ALTER TABLE worldcup_characters ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "worldcup_characters_read" ON worldcup_characters;
CREATE POLICY "worldcup_characters_read" ON worldcup_characters
  FOR SELECT USING (TRUE);

-- 세션 저장 테이블
CREATE TABLE IF NOT EXISTS worldcup_char_sessions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_key  TEXT NOT NULL,
  winner_id    BIGINT REFERENCES worldcup_characters(id),
  winner       TEXT NOT NULL,
  top4         JSONB,
  top4_tags    JSONB,
  lang         TEXT DEFAULT 'ko',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE worldcup_char_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "worldcup_char_sessions_insert" ON worldcup_char_sessions;
CREATE POLICY "worldcup_char_sessions_insert" ON worldcup_char_sessions
  FOR INSERT WITH CHECK (TRUE);
DROP POLICY IF EXISTS "worldcup_char_sessions_read" ON worldcup_char_sessions;
CREATE POLICY "worldcup_char_sessions_read" ON worldcup_char_sessions
  FOR SELECT USING (TRUE);


-- ═══════════════════════════════════════
-- 캐릭터 데이터 삽입 (225명)
-- ═══════════════════════════════════════

INSERT INTO worldcup_characters (category, name_ko, name_en, work_ko, work_en, tagline_ko, tagline_en, popularity_tier, archetype, trait, tone) VALUES
  ('protagonist', '몽키 D. 루피', 'Monkey D. Luffy', '원피스', 'One Piece', '바다 위의 자유를 꿈꾸는 고무인간', 'The rubber man chasing freedom across the seas', 'S', 'leader', 'freedom', 'bright'),
  ('protagonist', '우즈마키 나루토', 'Naruto Uzumaki', '나루토', 'Naruto', '외로움을 이겨낸 끈기의 닌자', 'The outcast ninja who never gave up', 'S', 'underdog', 'willpower', 'bright'),
  ('protagonist', '손오공', 'Goku', '드래곤볼', 'Dragon Ball', '싸움이 곧 삶인 순수한 전사', 'A pure warrior who lives to fight', 'S', 'berserker', 'instinct', 'playful'),
  ('protagonist', '쿠로사키 이치고', 'Ichigo Kurosaki', '블리치', 'Bleach', '지키고 싶은 것이 있는 사신대행', 'The substitute soul reaper with something to protect', 'S', 'guardian', 'pride', 'intense'),
  ('protagonist', '에렌 예거', 'Eren Yeager', '진격의 거인', 'Attack on Titan', '자유를 위해 괴물이 된 소년', 'The boy who became a monster for freedom', 'S', 'rebel', 'freedom', 'dark'),
  ('protagonist', '카마도 탄지로', 'Tanjiro Kamado', '귀멸의 칼날', 'Demon Slayer', '누구보다 따뜻한 귀살대원', 'The kindest demon slayer', 'S', 'guardian', 'sacrifice', 'warm'),
  ('protagonist', '이타도리 유지', 'Yuji Itadori', '주술회전', 'Jujutsu Kaisen', '올바른 죽음을 찾는 그릇', 'The vessel seeking righteous death', 'S', 'underdog', 'willpower', 'intense'),
  ('protagonist', '에드워드 엘릭', 'Edward Elric', '강철의 연금술사', 'FMA Brotherhood', '등가교환을 넘어선 꼬마 연금술사', 'The small alchemist who transcended equivalent exchange', 'S', 'seeker', 'intellect', 'bright'),
  ('protagonist', '덴지', 'Denji', '체인소맨', 'Chainsaw Man', '소박한 꿈을 위해 악마와 사는 소년', 'A boy living with devils for simple dreams', 'A', 'rebel', 'instinct', 'dark'),
  ('protagonist', '킬루아 조르딕', 'Killua Zoldyck', '헌터×헌터', 'Hunter x Hunter', '암살 가문을 벗어난 천재 소년', 'The genius boy who left his assassin family', 'A', 'genius', 'loyalty', 'cool'),
  ('protagonist', '히나타 쇼요', 'Hinata Shoyo', '하이큐', 'Haikyu!!', '작은 거인을 꿈꾸는 까마귀', 'The little giant who kept jumping', 'A', 'underdog', 'willpower', 'bright'),
  ('protagonist', '이사기 요이치', 'Isagi Yoichi', '블루록', 'Blue Lock', '이기적인 본능에 눈뜬 스트라이커', 'The striker who awakened his ego', 'A', 'genius', 'pride', 'intense'),
  ('protagonist', '사이타마', 'Saitama', '원펀맨', 'One Punch Man', '너무 강해서 지루한 영웅', 'The hero too strong to feel anything', 'A', 'wild_card', 'instinct', 'playful'),
  ('protagonist', '히비노 카프카', 'Kafka Hibino', '괴수8호', 'Kaiju No. 8', '늦깎이 괴수가 된 방위대 지망생', 'The late-blooming kaiju defense force hopeful', 'B', 'underdog', 'willpower', 'bright'),
  ('protagonist', '오카룬', 'Okarun', '단다단', 'DanDaDan', '초자연에 휘말린 순정파 소년', 'The pure-hearted boy caught in the supernatural', 'A', 'guardian', 'loyalty', 'warm'),
  ('protagonist', '아야세 세이코', 'Ayase Seiko', '단다단', 'DanDaDan', '손녀를 지키는 강인한 영매사 할머니', 'The tough spirit medium grandma protecting her granddaughter', 'B', 'sage', 'loyalty', 'warm'),
  ('protagonist', '미도리야 이즈쿠', 'Izuku Midoriya', '나의 히어로 아카데미아', 'My Hero Academia', '무개성에서 시작한 최고의 히어로', 'From quirkless to the greatest hero', 'B', 'underdog', 'sacrifice', 'bright'),
  ('protagonist', '가츠', 'Guts', '베르세르크', 'Berserk', '운명에 저항하는 검은 검사', 'The black swordsman defying fate', 'A', 'rebel', 'willpower', 'dark'),
  ('protagonist', '카네키 켄', 'Ken Kaneki', '도쿄구울', 'Tokyo Ghoul', '인간과 구울 사이에서 흔들리는 자', 'Torn between human and ghoul', 'A', 'stoic', 'empathy', 'melancholy'),
  ('protagonist', '토르핀', 'Thorfinn', '빈란드 사가', 'Vinland Saga', '복수를 버리고 평화를 찾아간 전사', 'The warrior who traded revenge for peace', 'B', 'seeker', 'freedom', 'melancholy'),
  ('protagonist', '이즈미 신이치', 'Shinichi Izumi', '기생수', 'Parasyte', '기생생물과 공존하게 된 고등학생', 'The student sharing his body with a parasite', 'B', 'stoic', 'intellect', 'dark'),
  ('protagonist', '이시가미 센쿠', 'Senku Ishigami', 'Dr. Stone', 'Dr. Stone', '과학으로 석기시대를 깨부수는 천재', 'The genius smashing the Stone Age with science', 'B', 'genius', 'intellect', 'bright'),
  ('protagonist', '쿠니미 히로', 'Hiro Kunimi', 'H2', 'H2', '야구와 사랑 사이에서 흔들리는 천재 투수', 'The genius pitcher torn between baseball and love', 'B', 'genius', 'pride', 'warm'),
  ('protagonist', '토미오카 기유', 'Giyu Tomioka', '귀멸의 칼날', 'Demon Slayer', '말없이 칼을 드는 물의 호흡 검사', 'The silent Water Breathing swordsman', 'B', 'stoic', 'loyalty', 'cool'),
  ('protagonist', '렌고쿠 쿄주로', 'Kyojuro Rengoku', '귀멸의 칼날', 'Demon Slayer', '마음을 불태워라 — 염주의 의지', '"Set your heart ablaze" — the Flame Pillar''s will', 'A', 'guardian', 'sacrifice', 'bright'),
  ('protagonist', '하타케 카카시', 'Kakashi Hatake', '나루토', 'Naruto', '제자를 지키는 카피 닌자', 'The Copy Ninja who protects his students', 'B', 'leader', 'loyalty', 'cool'),
  ('protagonist', '아바라이 렌지', 'Renji Abarai', '블리치', 'Bleach', '대장을 넘겠다는 붉은 머리 부대장', 'The red-haired lieutenant aiming to surpass his captain', 'B', 'underdog', 'loyalty', 'intense'),
  ('protagonist', '빈스모크 상디', 'Sanji Vinsmoke', '원피스', 'One Piece', '동료의 배를 채우는 발차기 요리사', 'The kick-fighting chef who feeds his crew', 'A', 'guardian', 'loyalty', 'playful'),
  ('protagonist', '손오반', 'Son Gohan', '드래곤볼', 'Dragon Ball', '아버지를 넘어선 혼혈 전사', 'The half-Saiyan who surpassed his father', 'B', 'guardian', 'sacrifice', 'bright'),
  ('protagonist', '후시구로 메구미', 'Megumi Fushiguro', '주술회전', 'Jujutsu Kaisen', '그림자로 싸우는 냉정한 주술사', 'The cool-headed sorcerer fighting with shadows', 'A', 'stoic', 'loyalty', 'cool'),
  ('protagonist', '바쿠고 카츠키', 'Katsuki Bakugo', '나의 히어로 아카데미아', 'My Hero Academia', 'No.1이 아니면 의미 없는 폭발 소년', 'The explosive boy who accepts nothing less than No.1', 'A', 'rebel', 'pride', 'intense'),
  ('protagonist', '아르민 알레르트', 'Armin Arlert', '진격의 거인', 'Attack on Titan', '두뇌로 세계를 바꾸려는 소년 병사', 'The boy soldier changing the world with his mind', 'B', 'genius', 'intellect', 'warm'),
  ('protagonist', '알폰스 엘릭', 'Alphonse Elric', '강철의 연금술사', 'FMA Brotherhood', '갑옷 안의 따뜻한 영혼', 'The warm soul inside the armor', 'B', 'guardian', 'empathy', 'warm'),
  ('protagonist', '곤 프릭스', 'Gon Freecss', '헌터×헌터', 'Hunter x Hunter', '아버지를 찾아 떠난 순수한 사냥꾼', 'The pure hunter who set out to find his father', 'S', 'underdog', 'instinct', 'bright'),
  ('protagonist', '카게야마 토비오', 'Tobio Kageyama', '하이큐', 'Haikyu!!', '코트의 왕이라 불린 천재 세터', 'The genius setter once called King of the Court', 'A', 'genius', 'pride', 'intense'),
  ('protagonist', '하야카와 아키', 'Aki Hayakawa', '체인소맨', 'Chainsaw Man', '복수를 위해 악마와 계약한 헌터', 'The hunter who contracted with devils for revenge', 'A', 'stoic', 'loyalty', 'dark'),
  ('protagonist', '쿠죠 죠타로', 'Jotaro Kujo', '죠죠의 기묘한 모험', 'JoJo''s Bizarre Adventure', '조용히 강한 스탠드 사용자', 'The quietly powerful Stand user', 'A', 'stoic', 'pride', 'cool'),
  ('protagonist', '로이드 포저', 'Loid Forger', '스파이×패밀리', 'Spy x Family', '가짜 가족에 진심이 된 최강의 스파이', 'The greatest spy who fell for his fake family', 'A', 'genius', 'loyalty', 'cool'),
  ('protagonist', '나츠 드래그닐', 'Natsu Dragneel', '페어리테일', 'Fairy Tail', '동료를 위해 불타는 화룡의 드래곤 슬레이어', 'The fire dragon slayer who burns for his friends', 'A', 'berserker', 'instinct', 'bright'),
  ('protagonist', '하나가키 타케미치', 'Takemichi Hanagaki', '도쿄 리벤저스', 'Tokyo Revengers', '과거를 바꿔 모두를 구하려는 시간 도약자', 'The time-leaper saving everyone by changing the past', 'A', 'underdog', 'willpower', 'bright'),
  ('protagonist', '텐마 켄조', 'Kenzo Tenma', '몬스터', 'Monster', '괴물을 구한 천재 의사의 속죄', 'The genius doctor atoning for saving a monster', 'A', 'guardian', 'sacrifice', 'warm'),
  ('protagonist', '코바야카와 세나', 'Sena Kobayakawa', '아이실드 21', 'Eyeshield 21', '겁쟁이가 광속 러너가 되기까지', 'From coward to lightning-speed runner', 'B', 'underdog', 'instinct', 'bright'),
  ('protagonist', '호시나 소시로', 'Soshiro Hoshina', '괴수8호', 'Kaiju No. 8', '3호 없이도 최강이었던 부대장', 'The vice-captain who was strongest even without No.3', 'B', 'genius', 'pride', 'cool'),
  ('protagonist', '바치라 메구루', 'Meguru Bachira', '블루록', 'Blue Lock', '괴물을 키우는 드리블 천재', 'The dribbling genius nurturing his inner monster', 'B', 'wild_card', 'instinct', 'playful'),
  ('protagonist', '제노스', 'Genos', '원펀맨', 'One Punch Man', '최강을 쫓는 사이보그 제자', 'The cyborg disciple chasing the strongest', 'B', 'guardian', 'loyalty', 'intense'),
  ('protagonist', '크누트', 'Canute', '빈란드 사가', 'Vinland Saga', '진정한 왕이 되려는 왕자', 'The prince striving to become a true king', 'B', 'leader', 'sacrifice', 'cool'),
  ('protagonist', '크롬', 'Chrome', 'Dr. Stone', 'Dr. Stone', '과학왕국의 원시인 과학자', 'The primitive scientist of the Kingdom of Science', 'B', 'underdog', 'intellect', 'bright'),
  ('protagonist', '그레이 풀버스터', 'Gray Fullbuster', '페어리테일', 'Fairy Tail', '얼음으로 싸우는 마도사', 'The ice mage who fights with freezing power', 'B', 'stoic', 'loyalty', 'cool'),
  ('protagonist', '니아', 'Near', '데스노트', 'Death Note', 'L의 의지를 이은 후계자', 'The successor who carried on L''s will', 'B', 'genius', 'intellect', 'cool'),
  ('protagonist', '히가시카타 죠스케', 'Josuke Higashikata', '죠죠의 기묘한 모험', 'JoJo''s Bizarre Adventure', '마음씨 좋은 불량 스탠드 사용자', 'The kind-hearted delinquent Stand user', 'B', 'guardian', 'loyalty', 'bright'),
  ('protagonist', '류구지 켄 (드라켄)', 'Ken Ryuguji (Draken)', '도쿄 리벤저스', 'Tokyo Revengers', '마이키를 지키는 충직한 부총장', 'The loyal vice-president who protects Mikey', 'B', 'guardian', 'loyalty', 'intense'),
  ('protagonist', '멜로', 'Mello', '데스노트', 'Death Note', 'L을 넘기 위해 수단을 가리지 않는 후계자', 'L''s successor who''d do anything to surpass him', 'B', 'rebel', 'obsession', 'intense'),
  ('protagonist', '세르피코', 'Serpico', '베르세르크', 'Berserk', '파른의 곁을 지키는 바람의 검사', 'The wind swordsman who guards Farnese', 'B', 'stoic', 'loyalty', 'cool'),
  ('protagonist', '아몬 코타로', 'Kotaro Amon', '도쿄구울', 'Tokyo Ghoul', '정의를 관철하려는 거구의 수사관', 'The towering investigator upholding justice', 'B', 'guardian', 'loyalty', 'intense'),
  ('protagonist', '미기', 'Migi', '기생수', 'Parasyte', '신이치의 오른손에 사는 냉정한 기생생물', 'The cool-headed parasyte in Shinichi''s right hand', 'B', 'genius', 'intellect', 'cool'),
  ('protagonist', '볼프강 그림머', 'Wolfgang Grimmer', '몬스터', 'Monster', '감정을 잃은 사나이의 마지막 미소', 'The emotionless man''s final smile', 'B', 'guardian', 'empathy', 'warm'),
  ('protagonist', '쿠리타 료칸', 'Ryokan Kurita', '아이실드 21', 'Eyeshield 21', '거구의 순둥이 라인맨', 'The gentle giant lineman', 'B', 'guardian', 'empathy', 'warm'),
  ('protagonist', '코가미 신야', 'Shinya Kogami', '사이코패스', 'Psycho-Pass', '시스템 밖에서 정의를 쫓는 집행관', 'The enforcer chasing justice outside the system', 'A', 'fighter', 'intellect', 'cool'),
  ('protagonist', '고죠 사토루', 'Satoru Gojo', '주술회전', 'Jujutsu Kaisen', '최강이라 외로운 주술사', 'The strongest sorcerer, lonely at the top', 'S', 'genius', 'pride', 'cool'),
  ('protagonist', '레비 아커만', 'Levi Ackerman', '진격의 거인', 'Attack on Titan', '인류 최강의 과묵한 병사', 'Humanity''s strongest, silent soldier', 'S', 'stoic', 'loyalty', 'cool'),
  ('protagonist', '쇼토 토도로키', 'Shoto Todoroki', '나의 히어로 아카데미아', 'My Hero Academia', '아버지의 그림자를 넘는 불과 얼음', 'Fire and ice overcoming a father''s shadow', 'A', 'stoic', 'pride', 'cool'),
  ('protagonist', '로로노아 조로', 'Roronoa Zoro', '원피스', 'One Piece', '세계 최강의 검사를 꿈꾸는 부선장', 'The first mate aiming to be the world''s greatest swordsman', 'A', 'stoic', 'loyalty', 'cool'),
  ('protagonist', '히루마 요이치', 'Yoichi Hiruma', '아이실드 21', 'Eyeshield 21', '악마적 두뇌의 전략가 쿼터백', 'The devilish strategist quarterback', 'B', 'trickster', 'intellect', 'playful'),
  ('protagonist', 'L', 'L', '데스노트', 'Death Note', '세계 최고의 탐정, 기행의 천재', 'The world''s greatest detective, an eccentric genius', 'B', 'genius', 'intellect', 'cool'),
  ('protagonist', '젠이츠 아가츠마', 'Zenitsu Agatsuma', '귀멸의 칼날', 'Demon Slayer', '겁쟁이지만 잠들면 최강', 'A coward who becomes the strongest when asleep', 'B', 'wild_card', 'instinct', 'playful'),
  ('protagonist', '츠키시마 케이', 'Kei Tsukishima', '하이큐', 'Haikyu!!', '냉소 뒤에 숨긴 열정의 미들블로커', 'The middle blocker hiding passion behind cynicism', 'B', 'genius', 'pride', 'cool'),
  ('protagonist', '시노미야 이사오', 'Isao Shinomiya', '괴수8호', 'Kaiju No. 8', '최강의 방위대장이자 미나의 아버지', 'The strongest defense force captain and Mina''s father', 'B', 'stoic', 'pride', 'cool'),
  ('protagonist', '이누야샤', 'InuYasha', '이누야샤', 'InuYasha', '사혼의 구슬을 쫓는 반요 소년', '', 'S', 'rebel', 'instinct', 'intense'),
  ('protagonist', '미로쿠', 'Miroku', '이누야샤', 'InuYasha', '풍혈을 짊어진 파계 법사', '', 'B', 'trickster', 'loyalty', 'playful'),
  ('protagonist', '우라메시 유스케', 'Yusuke Urameshi', '유유백서', 'Yu Yu Hakusho', '깡으로 살아가는 영계탐정', '', 'S', 'underdog', 'instinct', 'bright'),
  ('protagonist', '쿠라마', 'Kurama', '유유백서', 'Yu Yu Hakusho', '인간의 몸에 깃든 천년 여우요괴', '', 'A', 'genius', 'intellect', 'cool'),
  ('protagonist', '아시타카', 'Ashitaka', '모노노케히메', 'Princess Mononoke', '저주받은 팔로 공존을 찾는 에미시 왕자', '', 'A', 'seeker', 'sacrifice', 'warm'),
  ('protagonist', '산', 'San', '모노노케히메', 'Princess Mononoke', '인간을 증오하는 늑대의 딸', '', 'A', 'rebel', 'instinct', 'intense'),
  ('protagonist', '오미나에 유', 'Yu Ominae', '스프리건', 'Spriggan', '고교생이자 최강의 아캄 특수공작원', '', 'A', 'fighter', 'instinct', 'intense'),
  ('protagonist', '장 자크모', 'Jean Jacquemonde', '스프리건', 'Spriggan', '프랑스 출신 S급 스프리건', '', 'B', 'genius', 'intellect', 'cool'),
  ('protagonist', '사쿠라기 하나미치', 'Hanamichi Sakuragi', '슬램덩크', 'Slam Dunk', '천재라 불리고 싶은 빨간 머리 초보', '', 'S', 'underdog', 'instinct', 'bright'),
  ('protagonist', '루카와 카에데', 'Kaede Rukawa', '슬램덩크', 'Slam Dunk', '잠만 자는 천재 농구 선수', '', 'A', 'genius', 'pride', 'cool'),
  ('protagonist', '아무로 레이', 'Amuro Ray', '기동전사 건담', 'Mobile Suit Gundam', '뉴타입으로 각성한 건담의 파일럿', '', 'S', 'genius', 'willpower', 'intense'),
  ('protagonist', '브라이트 노아', 'Bright Noa', '기동전사 건담', 'Mobile Suit Gundam', '화이트베이스를 이끄는 젊은 함장', '', 'B', 'leader', 'loyalty', 'intense'),
  ('protagonist', '아마테라스', 'Amaterasu', '파이브스타스토리즈', 'Five Star Stories', '조커 성단의 빛의 신이자 방관하는 지배자', '', 'A', 'wild_card', 'intellect', 'melancholy'),
  ('protagonist', '콜러스 3세', 'Colus III', '파이브스타스토리즈', 'Five Star Stories', '하스하 연합 공화국의 대통령 기사', '', 'B', 'leader', 'pride', 'warm'),
  ('protagonist', '히무라 켄신', 'Kenshin Himura', '바람의 검심', 'Rurouni Kenshin', '불살의 맹세를 세운 전설의 인참', '', 'S', 'guardian', 'sacrifice', 'warm'),
  ('protagonist', '사가라 사노스케', 'Sanosuke Sagara', '바람의 검심', 'Rurouni Kenshin', '주먹 하나로 싸우는 전 적군 투사', '', 'B', 'rebel', 'loyalty', 'bright'),
  ('protagonist', '엔도 켄지', 'Kenji Endo', '20세기 소년', '20th Century Boys', '어릴 적 예언의 책을 쓴 평범한 편의점 주인', '', 'S', 'underdog', 'willpower', 'warm'),
  ('protagonist', '옷쵸', 'Otcho', '20세기 소년', '20th Century Boys', '켄지의 소꿉친구이자 태국에서 돌아온 전사', '', 'A', 'stoic', 'loyalty', 'cool'),
  ('protagonist', '우미노 미유키', 'Miyuki Umino', '해피', 'HAPPY!', '빚 2억 5천만엔을 갚기 위해 코트에 선 소녀', '', 'A', 'underdog', 'willpower', 'bright'),
  ('protagonist', '우미노 산페이', 'Sanpei Umino', '해피', 'HAPPY!', '미유키를 뒤에서 지탱하는 형', '', 'B', 'guardian', 'loyalty', 'warm'),
  ('protagonist', '스파이크 스피겔', 'Spike Spiegel', '카우보이 비밥', 'Cowboy Bebop', '과거를 등진 현상금 사냥꾼', '', 'S', 'rebel', 'instinct', 'cool'),
  ('protagonist', '제트 블랙', 'Jet Black', '카우보이 비밥', 'Cowboy Bebop', '비밥호의 선장이자 전직 형사', '', 'A', 'guardian', 'loyalty', 'warm'),
  ('protagonist', '아냐 포저', 'Anya Forger', '스파이×패밀리', 'Spy x Family', '마음을 읽는 꼬마 스파이', 'The little spy who reads minds', 'A', 'wild_card', 'empathy', 'playful'),
  ('protagonist', '히다카 하루카', 'Haruka Hidaka', 'H2', 'H2', '히로의 소꿉친구이자 서사의 또 다른 축', '', 'B', 'guardian', 'loyalty', 'warm'),
  ('protagonist', '기노자 노부치카', 'Nobuchika Ginoza', '사이코패스', 'Psycho-Pass', '감시관에서 집행관으로 — 정의의 형태가 바뀐 남자', '', 'B', 'guardian', 'loyalty', 'cool'),
  ('rival', '우치하 사스케', 'Sasuke Uchiha', '나루토', 'Naruto', '복수와 속죄 사이의 천재 닌자', 'The genius ninja torn between revenge and redemption', 'S', 'genius', 'pride', 'cool'),
  ('rival', '베지터', 'Vegeta', '드래곤볼', 'Dragon Ball', '자존심이 곧 힘인 사이어인 왕자', 'The Saiyan prince whose pride is his power', 'S', 'berserker', 'pride', 'intense'),
  ('rival', '야가미 라이토', 'Light Yagami', '데스노트', 'Death Note', '신이 되려 한 천재의 추락', 'The genius who fell trying to become God', 'S', 'mastermind', 'intellect', 'dark'),
  ('rival', '히소카', 'Hisoka', '헌터×헌터', 'Hunter x Hunter', '쾌락을 위해 사냥하는 변태 마술사', 'The twisted magician who hunts for pleasure', 'S', 'wild_card', 'chaos', 'playful'),
  ('rival', '아이젠 소스케', 'Sosuke Aizen', '블리치', 'Bleach', '모든 걸 꿰뚫어본 완벽한 흑막', 'The perfect mastermind who saw through everything', 'S', 'mastermind', 'intellect', 'cool'),
  ('rival', '마다라 우치하', 'Madara Uchiha', '나루토', 'Naruto', '전설이 된 최강의 시노비', 'The legendary shinobi who became myth', 'S', 'berserker', 'pride', 'intense'),
  ('rival', '우치하 이타치', 'Itachi Uchiha', '나루토', 'Naruto', '동생을 위해 악역을 연기한 천재', 'The genius who played villain for his brother', 'A', 'guardian', 'sacrifice', 'melancholy'),
  ('rival', '프리자', 'Frieza', '드래곤볼', 'Dragon Ball', '우주를 공포에 떨게 한 폭군', 'The tyrant who terrorized the universe', 'A', 'mastermind', 'pride', 'intense'),
  ('rival', '키사키 텟타', 'Tetta Kisaki', '도쿄 리벤저스', 'Tokyo Revengers', '모든 비극의 설계자', 'The architect of every tragedy', 'A', 'mastermind', 'obsession', 'dark'),
  ('rival', '그리피스', 'Griffith', '베르세르크', 'Berserk', '꿈을 위해 모든 걸 배신한 매', 'The hawk who betrayed everything for his dream', 'A', 'mastermind', 'obsession', 'dark'),
  ('rival', '요한 리베르트', 'Johan Liebert', '몬스터', 'Monster', '완벽한 악의 화신', 'The perfect embodiment of evil', 'A', 'mastermind', 'chaos', 'dark'),
  ('rival', '스카 (이슈발란)', 'Scar', '강철의 연금술사', 'FMA Brotherhood', '복수와 신앙 사이의 전사', 'A warrior between revenge and faith', 'B', 'rebel', 'obsession', 'dark'),
  ('rival', '디오 브란도', 'Dio Brando', '죠죠의 기묘한 모험', 'JoJo''s Bizarre Adventure', '인간을 초월하려 한 절대악', 'The absolute evil who sought to transcend humanity', 'B', 'mastermind', 'obsession', 'intense'),
  ('rival', '페인 (나가토)', 'Pain (Nagato)', '나루토', 'Naruto', '평화를 갈구한 신의 대리인', 'God''s agent who craved peace', 'B', 'rebel', 'sacrifice', 'dark'),
  ('rival', '키부츠지 무잔', 'Muzan Kibutsuji', '귀멸의 칼날', 'Demon Slayer', '천 년을 살아남은 모든 귀신의 시조', 'The progenitor of all demons who survived a thousand years', 'S', 'mastermind', 'obsession', 'dark'),
  ('rival', '아카자', 'Akaza', '귀멸의 칼날', 'Demon Slayer', '강함에 집착하는 비극의 상현귀', 'The tragic Upper Moon obsessed with strength', 'A', 'berserker', 'pride', 'intense'),
  ('rival', '울키오라 시퍼', 'Ulquiorra Cifer', '블리치', 'Bleach', '마음이 없었던 제4 에스파다', 'The 4th Espada who had no heart', 'A', 'stoic', 'chaos', 'melancholy'),
  ('rival', '돈키호테 도플라밍고', 'Donquixote Doflamingo', '원피스', 'One Piece', '하늘에서 세상을 조종한 천룡인', 'The Celestial Dragon who pulled strings from the sky', 'A', 'mastermind', 'pride', 'intense'),
  ('rival', '료멘 스쿠나', 'Ryomen Sukuna', '주술회전', 'Jujutsu Kaisen', '천 년에 한 번의 저주의 왕', 'The King of Curses — once in a thousand years', 'S', 'berserker', 'chaos', 'dark'),
  ('rival', '시가라키 토무라', 'Tomura Shigaraki', '나의 히어로 아카데미아', 'My Hero Academia', '영웅 사회를 무너뜨리려는 붕괴의 손', 'The hand of decay trying to destroy hero society', 'B', 'rebel', 'chaos', 'dark'),
  ('rival', '지크 예거', 'Zeke Yeager', '진격의 거인', 'Attack on Titan', '안락사 계획을 꿈꾼 형', 'The brother who dreamed of the euthanasia plan', 'B', 'mastermind', 'intellect', 'dark'),
  ('rival', '킹 브래들리', 'King Bradley', '강철의 연금술사', 'FMA Brotherhood', '분노의 호문클루스가 된 대총통', 'The Führer who was the homunculus of Wrath', 'A', 'berserker', 'pride', 'intense'),
  ('rival', '메루엠', 'Meruem', '헌터×헌터', 'Hunter x Hunter', '인간을 이해하게 된 개미의 왕', 'The Ant King who came to understand humanity', 'A', 'genius', 'empathy', 'melancholy'),
  ('rival', '오이카와 토오루', 'Toru Oikawa', '하이큐', 'Haikyu!!', '천재를 넘으려는 노력의 세터', 'The setter trying to surpass genius through effort', 'A', 'genius', 'obsession', 'intense'),
  ('rival', '마키마', 'Makima', '체인소맨', 'Chainsaw Man', '지배의 악마. 모든 걸 컨트롤하는 자', 'The Control Devil. She controls everything.', 'S', 'mastermind', 'obsession', 'cool'),
  ('rival', '아리마 키쇼', 'Kishou Arima', '도쿄구울', 'Tokyo Ghoul', 'CCG 최강 수사관, 사신', 'The CCG''s strongest investigator — the Reaper', 'A', 'genius', 'pride', 'cool'),
  ('rival', '키라 요시카게', 'Yoshikage Kira', '죠죠의 기묘한 모험', 'JoJo''s Bizarre Adventure', '조용한 일상을 원하는 연쇄살인마', 'The serial killer who just wants a quiet life', 'B', 'mastermind', 'obsession', 'dark'),
  ('rival', '제레프', 'Zeref', '페어리테일', 'Fairy Tail', '불사의 흑마도사', 'The immortal black wizard', 'B', 'mastermind', 'obsession', 'melancholy'),
  ('rival', '사노 만지로 (마이키)', 'Manjiro Sano (Mikey)', '도쿄 리벤저스', 'Tokyo Revengers', '무적의 마이키 — 빛과 어둠의 경계', 'Invincible Mikey — on the edge of light and dark', 'A', 'berserker', 'instinct', 'dark'),
  ('rival', '시시오 츠카사', 'Tsukasa Shishio', 'Dr. Stone', 'Dr. Stone', '구시대를 원하는 최강의 영장류', 'The strongest primate who wants the old world back', 'A', 'berserker', 'pride', 'intense'),
  ('rival', '아스켈라드', 'Askeladd', '빈란드 사가', 'Vinland Saga', '토르피안의 아버지를 죽인 책사', 'The schemer who killed Thorfinn''s father', 'A', 'trickster', 'intellect', 'cool'),
  ('rival', '타미야 료코', 'Ryoko Tamiya', '기생수', 'Parasyte', '인간 사회에 스며든 기생생물의 어머니', 'The parasyte mother who infiltrated human society', 'B', 'genius', 'intellect', 'cool'),
  ('rival', '타치바나 히데오', 'Hideo Tachibana', 'H2', 'H2', '히로의 영원한 라이벌이자 친구', 'Hiro''s eternal rival and friend', 'B', 'genius', 'pride', 'cool'),
  ('rival', '제라르 페르난데스', 'Jellal Fernandes', '페어리테일', 'Fairy Tail', '어둠에서 빛으로 돌아온 천재 마도사', 'The genius mage who returned from darkness to light', 'B', 'rebel', 'sacrifice', 'melancholy'),
  ('rival', '레제 (폭탄의 악마)', 'Reze (Bomb Devil)', '체인소맨', 'Chainsaw Man', '덴지의 첫사랑이자 폭탄의 악마', 'Denji''s first love and the Bomb Devil', 'B', 'trickster', 'sacrifice', 'melancholy'),
  ('rival', '토르켈', 'Thorkell', '빈란드 사가', 'Vinland Saga', '전쟁 자체를 즐기는 불멸의 거인', 'The immortal giant who fights for the joy of battle', 'B', 'berserker', 'instinct', 'playful'),
  ('rival', '스탠리 스나이더', 'Stanley Snyder', 'Dr. Stone', 'Dr. Stone', '총 하나로 과학군을 몰아붙인 군인', 'The soldier who cornered the science army alone', 'B', 'stoic', 'loyalty', 'intense'),
  ('rival', '노스페라투 조드', 'Nosferatu Zodd', '베르세르크', 'Berserk', '천 년을 산 전장의 불멸', 'The immortal of the battlefield for a millennium', 'B', 'berserker', 'pride', 'intense'),
  ('rival', '야모리 (제이슨)', 'Yamori (Jason)', '도쿄구울', 'Tokyo Ghoul', '카네키를 각성시킨 잔혹한 구울', 'The brutal ghoul who awakened Kaneki', 'B', 'berserker', 'chaos', 'dark'),
  ('rival', '고토', 'Gotou', '기생수', 'Parasyte', '5체 합성의 최강 기생생물', 'The ultimate parasyte — a fusion of five', 'B', 'berserker', 'instinct', 'dark'),
  ('rival', '가로우', 'Garou', '원펀맨', 'One Punch Man', '영웅사냥꾼 — 절대악을 자처한 구도자', 'The Hero Hunter — seeker claiming to be absolute evil', 'A', 'rebel', 'pride', 'intense'),
  ('rival', '보로스', 'Boros', '원펀맨', 'One Punch Man', '우주 최강을 찾아 떠돈 정복자', 'The alien conqueror who roamed space seeking the strongest', 'B', 'berserker', 'pride', 'intense'),
  ('rival', '이토시 린', 'Rin Itoshi', '블루록', 'Blue Lock', '형을 파괴하겠다는 천재 스트라이커', 'The genius striker who vows to destroy his brother', 'A', 'rebel', 'pride', 'intense'),
  ('rival', '나기 세이시로', 'Seishiro Nagi', '블루록', 'Blue Lock', '노력 없이 천재인 무기력 스트라이커', 'The effortlessly talented lethargic striker', 'B', 'genius', 'instinct', 'playful'),
  ('rival', '괴수9호', 'Kaiju No. 9', '괴수8호', 'Kaiju No. 8', '인간 사회에 침투한 지능형 괴수', 'The intelligent kaiju who infiltrated human society', 'A', 'mastermind', 'chaos', 'dark'),
  ('rival', '로베르토', 'Roberto', '몬스터', 'Monster', '요한의 충실한 그림자', 'Johan''s faithful shadow', 'B', 'stoic', 'obsession', 'dark'),
  ('rival', '진 세이주로', 'Seijuro Shin', '아이실드 21', 'Eyeshield 21', '세나의 영원한 라이벌 라인배커', 'Sena''s eternal rival linebacker', 'B', 'stoic', 'pride', 'intense'),
  ('rival', '마키시마 쇼고', 'Shogo Makishima', '사이코패스', 'Psycho-Pass', '시빌라의 맹점을 꿰뚫는 철학적 범죄자', 'The philosophical criminal exposing Sibyl''s blind spots', 'A', 'mastermind', 'chaos', 'elegant'),
  ('rival', '아크로바틱 찰랑찰랑', 'Acrobatic Chalrang', '단다단', 'Dandadan', '집착과 광기의 요괴', 'The yokai of obsession and madness', 'B', 'berserker', 'chaos', 'dark'),
  ('rival', '턱보 요괴', 'Turbo Granny', '단다단', 'Dandadan', '교활하고 장난기 넘치는 고대 요괴', 'The cunning and mischievous ancient yokai', 'B', 'trickster', 'instinct', 'comedic'),
  ('rival', '유리 브라이어', 'Yuri Briar', '스파이×패밀리', 'Spy x Family', '비밀경찰의 시스콘 요원', 'The siscon secret police agent', 'B', 'guardian', 'obsession', 'comedic'),
  ('rival', '가든 보스', 'Garden Boss', '스파이×패밀리', 'Spy x Family', '암살 조직의 냉철한 수장', 'The cold-blooded head of the assassination org', 'B', 'mastermind', 'intellect', 'dark'),
  ('rival', '마샬 D. 티치', 'Marshall D. Teach', '원피스', 'One Piece', '세계를 뒤흔드는 어둠의 사황', '', 'S', 'mastermind', 'obsession', 'dark'),
  ('rival', '켄자쿠', 'Kenjaku', '주술회전', 'Jujutsu Kaisen', '천 년을 살아온 저주의 흑막', '', 'A', 'mastermind', 'intellect', 'dark'),
  ('rival', '라이너 브라운', 'Reiner Braun', '진격의 거인', 'Attack on Titan', '전사와 병사 사이에서 갈라진 갑옷의 거인', '', 'A', 'guardian', 'sacrifice', 'melancholy'),
  ('rival', '올 포 원', 'All For One', '나의 히어로 아카데미아', 'My Hero Academia', '모든 개성을 빼앗는 절대악', '', 'S', 'mastermind', 'obsession', 'dark'),
  ('rival', '우시지마 와카토시', 'Wakatoshi Ushijima', '하이큐', 'Haikyu!!', '시라토리자와의 절대 에이스', '', 'A', 'stoic', 'pride', 'intense'),
  ('rival', '콘고 아곤', 'Agon Kongo', '아이실드 21', 'Eyeshield 21', '신속의 충동 — 0.11초의 천재', '', 'A', 'genius', 'pride', 'intense'),
  ('rival', '카무이 키리토', 'Kirito Kamui', '사이코패스', 'Psycho-Pass', '시빌라가 인식할 수 없는 투명한 존재', '', 'A', 'rebel', 'obsession', 'dark'),
  ('rival', '괴수10호', 'Kaiju No. 10', '괴수8호', 'Kaiju No. 8', '9호가 만들어낸 지능형 적대 괴수', '', 'B', 'berserker', 'instinct', 'dark'),
  ('rival', '테루 미카미', 'Teru Mikami', '데스노트', 'Death Note', '키라의 대리인 — 맹목적 정의의 광신자', '', 'B', 'guardian', 'loyalty', 'intense'),
  ('rival', '히로타 가츠토시', 'Katsutoshi Hirota', 'H2', 'H2', '승리를 위해 수단을 안 가리는 에이쿄 에이스', '', 'B', 'rebel', 'pride', 'intense'),
  ('rival', '나라쿠', 'Naraku', '이누야샤', 'InuYasha', '모든 비극을 설계한 반요의 흑막', '', 'S', 'mastermind', 'obsession', 'dark'),
  ('rival', '셋쇼마루', 'Sesshomaru', '이누야샤', 'InuYasha', '이누야샤의 형이자 완전한 대요괴', '', 'A', 'stoic', 'pride', 'cool'),
  ('rival', '토구로 동생', 'Younger Toguro', '유유백서', 'Yu Yu Hakusho', '100%의 힘을 추구하는 비극의 투사', '', 'A', 'berserker', 'willpower', 'dark'),
  ('rival', '센스이 시노부', 'Shinobu Sensui', '유유백서', 'Yu Yu Hakusho', '인류에 절망한 전 영계탐정', '', 'A', 'mastermind', 'chaos', 'dark'),
  ('rival', '에보시 고젠', 'Lady Eboshi', '모노노케히메', 'Princess Mononoke', '숲을 파괴하며 인간 문명을 세우는 지도자', '', 'A', 'leader', 'pride', 'cool'),
  ('rival', '지코보', 'Jigo', '모노노케히메', 'Princess Mononoke', '시시가미의 머리를 노리는 교활한 법사', '', 'B', 'trickster', 'intellect', 'playful'),
  ('rival', '보 브랜든', 'Bo Brandn', '스프리건', 'Spriggan', '미군 특수부대 코스모스의 지휘관', '', 'B', 'berserker', 'pride', 'intense'),
  ('rival', '래리 마크가드', 'Larry Markguard', '스프리건', 'Spriggan', '트라이던트의 냉혹한 에이전트', '', 'B', 'mastermind', 'obsession', 'dark'),
  ('rival', '센도 아키라', 'Akira Sendo', '슬램덩크', 'Slam Dunk', '료난의 천재 올라운더', '', 'A', 'genius', 'instinct', 'playful'),
  ('rival', '마키 신이치', 'Shinichi Maki', '슬램덩크', 'Slam Dunk', '가나가와 No.1 플레이어', '', 'A', 'leader', 'pride', 'intense'),
  ('rival', '샤아 아즈나블', 'Char Aznable', '기동전사 건담', 'Mobile Suit Gundam', '붉은 혜성 — 3배 빠른 복수자', '', 'S', 'mastermind', 'pride', 'cool'),
  ('rival', '기렌 자비', 'Gihren Zabi', '기동전사 건담', 'Mobile Suit Gundam', '지온을 이끄는 냉혹한 독재자', '', 'A', 'mastermind', 'obsession', 'dark'),
  ('rival', '보스야스포트', 'Bosjathforth', '파이브스타스토리즈', 'Five Star Stories', '성단을 뒤흔드는 야심의 기사', '', 'B', 'berserker', 'pride', 'intense'),
  ('rival', '하이아 미라즈', 'Haïa Mirage', '파이브스타스토리즈', 'Five Star Stories', '미라주 기사단의 그림자', '', 'B', 'mastermind', 'obsession', 'dark'),
  ('rival', '시시오 마코토', 'Makoto Shishio', '바람의 검심', 'Rurouni Kenshin', '약육강식을 신봉하는 전 인참의 후계자', '', 'S', 'mastermind', 'obsession', 'dark'),
  ('rival', '사이토 하지메', 'Hajime Saito', '바람의 검심', 'Rurouni Kenshin', '악즉참 — 신선조 3번대 대장', '', 'A', 'stoic', 'pride', 'cool'),
  ('rival', '토모다치', 'Friend', '20세기 소년', '20th Century Boys', '소년의 예언을 현실로 만든 가면의 교주', '', 'S', 'mastermind', 'obsession', 'dark'),
  ('rival', '카츠마타', 'Katsumata', '20세기 소년', '20th Century Boys', '두 번째 토모다치 — 세계 대통령의 그림자', '', 'A', 'mastermind', 'chaos', 'dark'),
  ('rival', '류가사키 초코', 'Choko Ryugasaki', '해피', 'HAPPY!', '명문가의 딸이자 미유키를 짓밟으려는 라이벌', '', 'B', 'genius', 'pride', 'intense'),
  ('rival', '오토리 우타코', 'Utako Ohtori', '해피', 'HAPPY!', '일본 테니스계를 지배하는 여제', '', 'B', 'mastermind', 'pride', 'cool'),
  ('rival', '비셔스', 'Vicious', '카우보이 비밥', 'Cowboy Bebop', '레드 드래곤의 정점에 선 냉혈한 옛 동료', '', 'A', 'mastermind', 'instinct', 'dark'),
  ('rival', '피에르 르 푸', 'Pierrot Le Fou', '카우보이 비밥', 'Cowboy Bebop', '웃으며 죽이는 광기의 암살자', '', 'B', 'wild_card', 'chaos', 'dark'),
  ('female', '미카사 아커만', 'Mikasa Ackerman', '진격의 거인', 'Attack on Titan', '모든 걸 바쳐 지키는 최강의 병사', 'The strongest soldier who gave everything to protect', 'S', 'guardian', 'loyalty', 'intense'),
  ('female', '나미', 'Nami', '원피스', 'One Piece', '바다의 지도를 그리는 항해사', 'The navigator charting the sea', 'S', 'trickster', 'intellect', 'bright'),
  ('female', '쿠기사키 노바라', 'Nobara Kugisaki', '주술회전', 'Jujutsu Kaisen', '자기답게 사는 게 최강인 소녀', 'The girl whose strength is being herself', 'S', 'rebel', 'pride', 'bright'),
  ('female', '히나타 휴우가', 'Hinata Hyuga', '나루토', 'Naruto', '조용한 용기로 성장한 소녀', 'The girl who grew through quiet courage', 'S', 'underdog', 'loyalty', 'warm'),
  ('female', '불마', 'Bulma', '드래곤볼', 'Dragon Ball', '천재 과학자이자 모험의 시작', 'The genius scientist who started it all', 'S', 'genius', 'intellect', 'playful'),
  ('female', '에르자 스칼렛', 'Erza Scarlet', '페어리테일', 'Fairy Tail', '갑옷 뒤에 숨긴 따뜻한 마음', 'A warm heart hidden behind armor', 'S', 'leader', 'loyalty', 'intense'),
  ('female', '츠유 아스이', 'Tsuyu Asui', '나의 히어로 아카데미아', 'My Hero Academia', '냉정하고 솔직한 개구리 히어로', 'The cool and honest frog hero', 'A', 'stoic', 'loyalty', 'cool'),
  ('female', '로빈 니코', 'Nico Robin', '원피스', 'One Piece', '살고 싶다고 외친 고고학자', 'The archaeologist who cried "I want to live"', 'A', 'seeker', 'intellect', 'melancholy'),
  ('female', '루키아 쿠치키', 'Rukia Kuchiki', '블리치', 'Bleach', '이치고에게 힘을 준 사신', 'The soul reaper who gave Ichigo his power', 'A', 'guardian', 'sacrifice', 'cool'),
  ('female', '시노부 코초', 'Shinobu Kocho', '귀멸의 칼날', 'Demon Slayer', '웃음 뒤에 분노를 숨긴 독충주', 'The insect pillar hiding rage behind a smile', 'A', 'trickster', 'sacrifice', 'cool'),
  ('female', '마키 제닌', 'Maki Zenin', '주술회전', 'Jujutsu Kaisen', '가문을 부순 무술식의 전사', 'The curseless warrior who destroyed her clan', 'A', 'rebel', 'pride', 'intense'),
  ('female', '모모시키 아야세', 'Ayase Momoshiki', '단다단', 'DanDaDan', '오컬트에 미친 강한 소녀', 'The occult-obsessed powerhouse girl', 'A', 'wild_card', 'instinct', 'bright'),
  ('female', '호크 아이 리자', 'Riza Hawkeye', '강철의 연금술사', 'FMA Brotherhood', '총 뒤에서 대령을 지키는 눈', 'The watchful eye protecting the Colonel', 'A', 'guardian', 'loyalty', 'cool'),
  ('female', '츠나데', 'Tsunade', '나루토', 'Naruto', '전설의 3닌 중 최강의 의료닌자', 'The strongest medical ninja of the Legendary Three', 'B', 'leader', 'sacrifice', 'intense'),
  ('female', '요르 포저', 'Yor Forger', '스파이×패밀리', 'Spy x Family', '가족을 위해 싸우는 암살자 엄마', 'The assassin mom who fights for her family', 'B', 'guardian', 'loyalty', 'warm'),
  ('female', '오리히메 이노우에', 'Orihime Inoue', '블리치', 'Bleach', '거부의 힘을 가진 치유자', 'The healer with the power of rejection', 'B', 'healer', 'empathy', 'warm'),
  ('female', '우라라카 오차코', 'Ochaco Uraraka', '나의 히어로 아카데미아', 'My Hero Academia', '무중력 소녀의 현실적인 꿈', 'The zero-gravity girl with realistic dreams', 'B', 'underdog', 'willpower', 'bright'),
  ('female', '요루이치 시호인', 'Yoruichi Shihoin', '블리치', 'Bleach', '번개처럼 빠른 전 은밀기동대 총사령관', 'The lightning-fast former stealth force commander', 'B', 'genius', 'freedom', 'playful'),
  ('female', '코난', 'Konan', '나루토', 'Naruto', '종이 꽃 속에 숨긴 의지', 'The will hidden within paper flowers', 'B', 'guardian', 'sacrifice', 'melancholy'),
  ('female', '레비 맥거딘', 'Levy McGarden', '페어리테일', 'Fairy Tail', '문자 마법을 쓰는 작은 천재', 'The tiny genius who wields word magic', 'B', 'healer', 'intellect', 'warm'),
  ('female', '아마미야 히카리', 'Hikari Amamiya', 'H2', 'H2', '야구소년의 곁을 지키는 당찬 매니저', 'The spirited manager standing by the baseball boy', 'B', 'guardian', 'loyalty', 'warm'),
  ('female', '코무기', 'Komugi', '헌터×헌터', 'Hunter x Hunter', '왕의 마음을 바꾼 군기 소녀', 'The Gungi girl who changed the king''s heart', 'B', 'healer', 'empathy', 'warm'),
  ('female', '시미즈 키요코', 'Kiyoko Shimizu', '하이큐', 'Haikyu!!', '카라스노의 여신 매니저', 'The goddess manager of Karasuno', 'B', 'stoic', 'loyalty', 'cool'),
  ('female', '캐스카', 'Casca', '베르세르크', 'Berserk', '매의 단에서 가장 강한 여전사', 'The strongest warrior of the Band of the Hawk', 'A', 'guardian', 'loyalty', 'intense'),
  ('female', '파워', 'Power', '체인소맨', 'Chainsaw Man', '혈의 마인 — 자칭 파워님이시다', 'The Blood Fiend — self-proclaimed Power-sama', 'A', 'wild_card', 'chaos', 'playful'),
  ('female', '키리시마 토카', 'Touka Kirishima', '도쿄구울', 'Tokyo Ghoul', '카네키 곁의 토끼 구울', 'The rabbit ghoul by Kaneki''s side', 'B', 'rebel', 'loyalty', 'dark'),
  ('female', '쿠죠 죠린', 'Jolyne Cujoh', '죠죠의 기묘한 모험', 'JoJo''s Bizarre Adventure', '아버지의 뜻을 잇는 여성 죠죠', 'The female JoJo carrying on her father''s will', 'B', 'rebel', 'willpower', 'intense'),
  ('female', '타치바나 히나타', 'Hinata Tachibana', '도쿄 리벤저스', 'Tokyo Revengers', '타케미치가 지키려는 첫사랑', 'The first love Takemichi fights to save', 'B', 'healer', 'empathy', 'warm'),
  ('female', '아마네 미사', 'Misa Amane', '데스노트', 'Death Note', '라이토를 향한 맹목의 제2 키라', 'The blind devotion of the Second Kira', 'B', 'wild_card', 'obsession', 'dark'),
  ('female', '츠네모리 아카네', 'Akane Tsunemori', '사이코패스', 'Psycho-Pass', '정의를 지키는 감시관', 'The inspector who upholds justice', 'B', 'guardian', 'empathy', 'intense'),
  ('female', '구드리드', 'Gudrid', '빈란드 사가', 'Vinland Saga', '토르피안과 함께 꿈꾸는 여행자', 'The traveler who dreams alongside Thorfinn', 'B', 'seeker', 'freedom', 'warm'),
  ('female', '미나 아시로', 'Mina Ashiro', '괴수8호', 'Kaiju No. 8', '방위대 최강의 대장', 'The strongest captain of the Defense Force', 'B', 'leader', 'willpower', 'intense'),
  ('female', '코하쿠', 'Kohaku', 'Dr. Stone', 'Dr. Stone', '석기시대 최강의 소녀 전사', 'The strongest girl warrior of the Stone Age', 'B', 'guardian', 'empathy', 'bright'),
  ('female', '무라노 사토미', 'Satomi Murano', '기생수', 'Parasyte', '신이치가 지키고 싶은 일상의 상징', 'The symbol of everyday life Shinichi wants to protect', 'B', 'healer', 'empathy', 'warm'),
  ('female', '타츠마키', 'Tatsumaki', '원펀맨', 'One Punch Man', 'S급 2위 — 초능력의 폭풍', 'S-Class Rank 2 — the Psychic Storm', 'A', 'genius', 'pride', 'intense'),
  ('female', '니나 포르트나', 'Nina Fortner', '몬스터', 'Monster', '쌍둥이 오빠의 비밀을 쫓는 소녀', 'The girl chasing the secret of her twin brother', 'B', 'seeker', 'empathy', 'warm'),
  ('female', '아네자키 마모리', 'Mamori Anezaki', '아이실드 21', 'Eyeshield 21', '세나를 지키는 데빌배츠 매니저', 'The Devil Bats manager who protects Sena', 'B', 'guardian', 'loyalty', 'warm'),
  ('female', '테이에리 안리', 'Anri Teieri', '블루록', 'Blue Lock', '블루록 프로젝트의 냉철한 분석가', 'The cool-headed analyst of Blue Lock project', 'B', 'mastermind', 'intellect', 'cool'),
  ('female', '히구라시 카고메', 'Kagome Higurashi', '이누야샤', 'InuYasha', '시대를 넘어 사혼의 구슬을 쫓는 무녀', '', 'S', 'guardian', 'empathy', 'warm'),
  ('female', '유키무라 케이코', 'Keiko Yukimura', '유유백서', 'Yu Yu Hakusho', '유스케를 기다리는 강한 소꿉친구', '', 'B', 'guardian', 'loyalty', 'warm'),
  ('female', '카야', 'Kaya', '모노노케히메', 'Princess Mononoke', '아시타카를 떠나보낸 에미시 마을의 소녀', '', 'B', 'healer', 'empathy', 'warm'),
  ('female', '티아 플랫', 'Tia Flat', '스프리건', 'Spriggan', '마녀라 불리는 여성 스프리건', '', 'B', 'genius', 'intellect', 'cool'),
  ('female', '아카기 하루코', 'Haruko Akagi', '슬램덩크', 'Slam Dunk', '사쿠라기를 농구로 이끈 매니저', '', 'B', 'healer', 'empathy', 'warm'),
  ('female', '세이라 마스', 'Sayla Mass', '기동전사 건담', 'Mobile Suit Gundam', '샤아의 여동생이자 화이트베이스 크루', '', 'B', 'guardian', 'loyalty', 'cool'),
  ('female', '라키시스', 'Lachesis', '파이브스타스토리즈', 'Five Star Stories', '아마테라스와 함께하는 운명의 파티마', '', 'A', 'seeker', 'empathy', 'melancholy'),
  ('female', '카미야 카오루', 'Kaoru Kamiya', '바람의 검심', 'Rurouni Kenshin', '검심의 귀환할 곳을 지키는 검도장 주인', '', 'A', 'guardian', 'loyalty', 'warm'),
  ('female', '칸나 엔도', 'Kanna Endo', '20세기 소년', '20th Century Boys', '삼촌의 뜻을 이어 토모다치에 맞서는 소녀', '', 'A', 'rebel', 'sacrifice', 'intense'),
  ('female', '우미노 미유키', 'Miyuki Umino', '해피', 'HAPPY!', '빚 2억 5천만엔을 갚기 위해 코트에 선 소녀', '', 'A', 'underdog', 'willpower', 'bright'),
  ('female', '페이 발렌타인', 'Faye Valentine', '카우보이 비밥', 'Cowboy Bebop', '기억을 잃은 채 떠도는 도박사 현상금 사냥꾼', '', 'A', 'trickster', 'freedom', 'cool');


-- AniList ID 매핑 (주요 캐릭터)

UPDATE worldcup_characters SET anilist_id = 71 WHERE name_ko = 'L';
UPDATE worldcup_characters SET anilist_id = 422 WHERE name_ko = '가츠';
UPDATE worldcup_characters SET anilist_id = 423 WHERE name_ko = '그리피스';
UPDATE worldcup_characters SET anilist_id = 1159 WHERE name_ko = '나라쿠';
UPDATE worldcup_characters SET anilist_id = 723 WHERE name_ko = '나미';
UPDATE worldcup_characters SET anilist_id = 5187 WHERE name_ko = '나츠 드래그닐';
UPDATE worldcup_characters SET anilist_id = 127208 WHERE name_ko = '덴지';
UPDATE worldcup_characters SET anilist_id = 11362 WHERE name_ko = '디오 브란도';
UPDATE worldcup_characters SET anilist_id = 46498 WHERE name_ko = '라이너 브라운';
UPDATE worldcup_characters SET anilist_id = 61 WHERE name_ko = '로빈 니코';
UPDATE worldcup_characters SET anilist_id = 417 WHERE name_ko = '루루슈 람페로우지';
UPDATE worldcup_characters SET anilist_id = 66 WHERE name_ko = '리자 호크아이';
UPDATE worldcup_characters SET anilist_id = 11746 WHERE name_ko = '마다라 우치하';
UPDATE worldcup_characters SET anilist_id = 46497 WHERE name_ko = '마샬 D. 티치';
UPDATE worldcup_characters SET anilist_id = 148301 WHERE name_ko = '마키마';
UPDATE worldcup_characters SET anilist_id = 68411 WHERE name_ko = '마키시마 쇼고';
UPDATE worldcup_characters SET anilist_id = 175712 WHERE name_ko = '모모시키 아야세';
UPDATE worldcup_characters SET anilist_id = 40 WHERE name_ko = '몽키 D. 루피';
UPDATE worldcup_characters SET anilist_id = 89028 WHERE name_ko = '미도리야 이즈쿠';
UPDATE worldcup_characters SET anilist_id = 40881 WHERE name_ko = '미카사 아커만';
UPDATE worldcup_characters SET anilist_id = 89220 WHERE name_ko = '바쿠고 카츠키';
UPDATE worldcup_characters SET anilist_id = 3636 WHERE name_ko = '베지터';
UPDATE worldcup_characters SET anilist_id = 2490 WHERE name_ko = '불마';
UPDATE worldcup_characters SET anilist_id = 2 WHERE name_ko = '비셔스';
UPDATE worldcup_characters SET anilist_id = 203 WHERE name_ko = '비앙카 탱크스';
UPDATE worldcup_characters SET anilist_id = 73935 WHERE name_ko = '사이타마';
UPDATE worldcup_characters SET anilist_id = 2478 WHERE name_ko = '사쿠라기 하나미치';
UPDATE worldcup_characters SET anilist_id = 1012 WHERE name_ko = '산 (모노노케히메)';
UPDATE worldcup_characters SET anilist_id = 2472 WHERE name_ko = '센도 아키라';
UPDATE worldcup_characters SET anilist_id = 2492 WHERE name_ko = '손오공';
UPDATE worldcup_characters SET anilist_id = 45 WHERE name_ko = '스카 (이슈발란)';
UPDATE worldcup_characters SET anilist_id = 1 WHERE name_ko = '스파이크 스피겔';
UPDATE worldcup_characters SET anilist_id = 89429 WHERE name_ko = '시가라키 토무라';
UPDATE worldcup_characters SET anilist_id = 8523 WHERE name_ko = '시시오 마코토';
UPDATE worldcup_characters SET anilist_id = 138101 WHERE name_ko = '아냐 포저';
UPDATE worldcup_characters SET anilist_id = 11261 WHERE name_ko = '아무로 레이';
UPDATE worldcup_characters SET anilist_id = 1002 WHERE name_ko = '아시타카';
UPDATE worldcup_characters SET anilist_id = 1828 WHERE name_ko = '아이젠 소스케';
UPDATE worldcup_characters SET anilist_id = 80 WHERE name_ko = '야가미 라이토';
UPDATE worldcup_characters SET anilist_id = 11 WHERE name_ko = '에드워드 엘릭';
UPDATE worldcup_characters SET anilist_id = 40882 WHERE name_ko = '에렌 예거';
UPDATE worldcup_characters SET anilist_id = 5190 WHERE name_ko = '에르자 스칼렛';
UPDATE worldcup_characters SET anilist_id = 1992 WHERE name_ko = '엔도 켄지';
UPDATE worldcup_characters SET anilist_id = 1274 WHERE name_ko = '오리히메 이노우에';
UPDATE worldcup_characters SET anilist_id = 78093 WHERE name_ko = '오이카와 토오루';
UPDATE worldcup_characters SET anilist_id = 175714 WHERE name_ko = '오카룬';
UPDATE worldcup_characters SET anilist_id = 138102 WHERE name_ko = '요르 포저';
UPDATE worldcup_characters SET anilist_id = 438 WHERE name_ko = '요한 리베르트';
UPDATE worldcup_characters SET anilist_id = 89221 WHERE name_ko = '우라라카 오차코';
UPDATE worldcup_characters SET anilist_id = 17 WHERE name_ko = '우즈마키 나루토';
UPDATE worldcup_characters SET anilist_id = 173599 WHERE name_ko = '이사기 요이치';
UPDATE worldcup_characters SET anilist_id = 127691 WHERE name_ko = '이타도리 유지';
UPDATE worldcup_characters SET anilist_id = 4003 WHERE name_ko = '죠타로 쿠죠';
UPDATE worldcup_characters SET anilist_id = 13 WHERE name_ko = '츠나데';
UPDATE worldcup_characters SET anilist_id = 68409 WHERE name_ko = '츠네모리 아카네';
UPDATE worldcup_characters SET anilist_id = 87275 WHERE name_ko = '카네키 켄';
UPDATE worldcup_characters SET anilist_id = 128532 WHERE name_ko = '카마도 탄지로';
UPDATE worldcup_characters SET anilist_id = 425 WHERE name_ko = '캐스카';
UPDATE worldcup_characters SET anilist_id = 2728 WHERE name_ko = '켄시로';
UPDATE worldcup_characters SET anilist_id = 127691 WHERE name_ko = '코하쿠';
UPDATE worldcup_characters SET anilist_id = 307 WHERE name_ko = '쿠로사키 이치고';
UPDATE worldcup_characters SET anilist_id = 45627 WHERE name_ko = '쿠죠 죠린';
UPDATE worldcup_characters SET anilist_id = 21715 WHERE name_ko = '키라 요시카게';
UPDATE worldcup_characters SET anilist_id = 138095 WHERE name_ko = '키부츠지 무잔';
UPDATE worldcup_characters SET anilist_id = 140709 WHERE name_ko = '키사키 텟타';
UPDATE worldcup_characters SET anilist_id = 27 WHERE name_ko = '킬루아 조르딕';
UPDATE worldcup_characters SET anilist_id = 448 WHERE name_ko = '텐마 켄조';
UPDATE worldcup_characters SET anilist_id = 65849 WHERE name_ko = '토르핀';
UPDATE worldcup_characters SET anilist_id = 1994 WHERE name_ko = '토모다치';
UPDATE worldcup_characters SET anilist_id = 127210 WHERE name_ko = '파워';
UPDATE worldcup_characters SET anilist_id = 2491 WHERE name_ko = '프리저';
UPDATE worldcup_characters SET anilist_id = 140685 WHERE name_ko = '하나가키 타케미치';
UPDATE worldcup_characters SET anilist_id = 66583 WHERE name_ko = '히나타 쇼요';
UPDATE worldcup_characters SET anilist_id = 234 WHERE name_ko = '히나타 휴우가';
UPDATE worldcup_characters SET anilist_id = 81 WHERE name_ko = '히무라 켄신';
UPDATE worldcup_characters SET anilist_id = 160979 WHERE name_ko = '히비노 카프카';
UPDATE worldcup_characters SET anilist_id = 30 WHERE name_ko = '히소카';
